services:
  api:
    build: ./backend
    container_name: rideflow_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/rideflow
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgis/postgis:15-3.3
    container_name: rideflow_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rideflow
    volumes:
      - rideflow_db_content:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rideflow_redis
    ports:
      - "6379:6379"

volumes:
  rideflow_db_content:
